name: new_website
description: Puzzak.Page 2.0
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.10
  intl: ^0.18.0
  dynamic_color: ^1.6.9
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/authors.json
    - assets/puzzak_av.jpg
    - assets/profile.jpg
    - assets/dashboard-project.png
    - assets/autostream-project.png
    - assets/links-project.png
    - assets/map-project.png
    - assets/secret-project.png
    - pubspec.yaml
